const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{element,content}=require('./dom-harness.cjs'),geom=require('../js/geomorphology.js'),geometry=require('../js/geometry.js');
const data=JSON.parse(fs.readFileSync('data/processed/cprm/padroes-relevo.geojson','utf8'));
async function report({work=false,visibleRelief=true,noTiles=false,imageFailure=false,outside=false}={}){
  const selected={feature:structuredClone(data.features.find(f=>f.properties.PADRAO==='Colinas')),title:'Colinas selecionadas',meta:{layerId:work?undefined:'relevo',source:geom.source,work},context:{municipio:'Niterói/RJ'},metrics:{lat:-22.92,lon:-43.04,type:'Polygon',area:12345},ref:{lat:-22.92,lng:-43.04}};
  selected.feature.properties.CPF='NÃO PUBLICAR';selected.feature.properties.inventado='NÃO PUBLICAR';
  const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,element('div'));return nodes.get(id)},visible={},hidden={},relief={};
  const ctx={document:{getElementById:node,createElement:element,querySelectorAll:()=>[]},element,content,map:{getContainer:()=>element('map'),hasLayer:l=>l===visible||visibleRelief&&l===relief,getZoom:()=>17,distance:()=>100,containerPointToLatLng:p=>p},ARPIASUI:{selection:()=>selected,fitSelection(){},workGroup:{getLayers:()=>work?[visible]:[]},measurementRows:()=>[['Área estimada','12345']],publicAttributes:geometry.publicAttributes,distanceLabel:n=>n+' m',visibleLegend:()=>element('div',visibleRelief?geom.legendWarning:'')},overlayDefs:[{name:'Bairros visíveis',layer:{...visible,options:{},eachFeature(){}}},{name:'Lotes ocultos',layer:{...hidden,options:{},eachFeature(){}}}],civilDefs:[],reliefDefs:[{name:'Padrões de Relevo',layer:relief,source:geom.source}],ARPIASGeometry:geometry,ARPIASGeomorphology:geom,ARPIASTurf:require('@turf/turf'),ARPIASLocation:require('../js/location.js'),activeBaseDef:{id:'ortho',name:'Foto Aérea 2019',layer:{isLoading:()=>false}},recentDate:'2026-09-29',location:{href:'http://127.0.0.1:8080/'},requestAnimationFrame:f=>f(),setTimeout,clearTimeout,toast(){},console,safeName:p=>p.nome};
  // Preserve identities when testing actual map membership.
  const tile=element('img');Object.assign(tile,{complete:true,naturalWidth:256,src:'fixture-tile'});
  ctx.document.querySelectorAll=selector=>selector==='#map img.leaflet-tile-loaded'&&!noTiles?[tile]:[];
  ctx.map.getPane=()=>({querySelectorAll:()=>[]});
  ctx.Image=class{set src(value){queueMicrotask(()=>imageFailure?this.onerror():this.onload())}};
  ctx.ARPIASUI.selectionBounds=()=>({});ctx.map.getBounds=()=>({contains:()=>!outside});
  ctx.ARPIASUI.fitSelection=()=>assert.fail('Report must not reframe the map');
  ctx.console={error(){}};
  ctx.overlayDefs[0].layer=visible;visible.options={};visible.eachFeature=()=>{};ctx.overlayDefs[1].layer=hidden;hidden.options={};hidden.eachFeature=()=>{};
  vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/report.js','utf8')+'\nthis.report=ARPIASReport;',ctx);await ctx.report.generate();return {body:node('reportBody'),selected,nodes,api:ctx.report};
}
test('real report.js uses selected geometry and excludes hidden layers and nonexistent/private attributes',async()=>{const {body,nodes}=await report();assert.match(body.textContent,/Colinas selecionadas/);assert.match(body.textContent,/R4a1/);assert.match(body.textContent,/Bairros visíveis/);assert.doesNotMatch(body.textContent,/Lotes ocultos|CPF|inventado|NÃO PUBLICAR/);assert.equal(nodes.get('printReport').disabled,false);assert.ok(body.children.some(n=>n.className==='report-map'&&n.src.startsWith('data:image/png')))});
test('selected relief retains source year scale and methodological warning even when its overlay is hidden',async()=>{const {body}=await report({visibleRelief:false});assert.match(body.textContent,/CPRM/);assert.match(body.textContent,/2017/);assert.match(body.textContent,/1:30.000/);assert.match(body.textContent,/Não substitui mapeamento atualizado de risco/);assert.doesNotMatch(body.textContent,/Padrões de Relevo Camada ativada/)});
test('real report marks selected working geometry and visible work layers as non-official',async()=>{const {body}=await report({work:true});assert.match(body.textContent,/Geometria de trabalho \/ não oficial/);assert.match(body.textContent,/Camadas de trabalho \/ não oficiais/)});

test('report refuses an empty basemap instead of exporting a misleading image',async()=>{const {body,nodes}=await report({noTiles:true});assert.match(body.textContent,/sem imagem carregada/);assert.equal(nodes.get('printReport').disabled,true);assert.equal(body.children.some(n=>n.className==='report-map'),false)});
test('capture rejection is explicit and does not enable PDF printing',async()=>{const {body,nodes}=await report({imageFailure:true});assert.match(body.textContent,/Imagem sem acesso para exportação/);assert.equal(nodes.get('printReport').disabled,true)});
test('selection outside the frame requests framing without mutating the view',async()=>{const {body,nodes}=await report({outside:true});assert.match(body.textContent,/Enquadre a seleção/);assert.equal(nodes.get('printReport').disabled,true)});
