const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),geom=require('../js/geomorphology.js'),catalog=require('../js/catalog.js'),{element,Element}=require('./dom-harness.cjs');
const data=JSON.parse(fs.readFileSync('data/processed/cprm/padroes-relevo.geojson','utf8')),app=fs.readFileSync('js/app.js','utf8'),tools=fs.readFileSync('js/tools.js','utf8');
test('relief is lazy and concurrent requests and classifications share a single download',async()=>{let calls=0;const load=geom.createLoader(async()=>{calls++;return data});assert.equal(calls,0);const [a,b]=await Promise.all([load(),load()]);assert.equal(a,b);for(const field of Object.keys(geom.fields))geom.classes(await load(),field);assert.equal(calls,1);assert.equal(await load(),data)});
test('a failed relief download rejects without poisoning the cache and can be retried',async()=>{let calls=0;const load=geom.createLoader(async()=>{if(++calls===1)throw Error('offline');return data});await assert.rejects(load(),/offline/);assert.equal(await load(),data);assert.equal(calls,2)});
test('initial app setup only declares a loader and a failure leaves the map usable',async()=>{
  const ctx={readJSON:async()=>{throw Error('offline')},ARPIASGeomorphology:geom,relief:{input:{checked:true},status:element('small')},reliefRow:element('div'),reliefMessage:element('p'),toast(){},console:{error(){}}};vm.createContext(ctx);
  vm.runInContext(app.slice(app.indexOf('const fetchRelief='),app.indexOf('const catalogHost=')),ctx);
  assert.equal(ctx.relief.loading,undefined);assert.equal(await ctx.loadRelief(),null);assert.equal(ctx.relief.input.checked,false);assert.match(ctx.reliefMessage.textContent,/Não foi possível carregar/);assert.equal(ctx.reliefRow.attributes['aria-busy'],'false');
});
test('public catalog states never advertise an item without a control as a map layer',()=>{
  for(const item of require('../data/catalogo.json').groups.flatMap(g=>g.items)){const state=catalog.publicStatus(item);assert.ok(['DISPONÍVEL NO MAPA','FONTE IDENTIFICADA','EM INTEGRAÇÃO','METODOLOGIA EM DESENVOLVIMENTO'].includes(state));if(state==='DISPONÍVEL NO MAPA')assert.ok(item.control&&item.state==='integrated');}
  assert.equal(catalog.publicStatus({state:'integrated'}),'EM INTEGRAÇÃO');assert.equal(catalog.operationalStatus('Dados em carregamento'),'◐ EM INTEGRAÇÃO');
  assert.doesNotMatch(app,/teste no mapa pendente|Teste pendente|Teste de carregamento pendente|Dados em validação|Ver fachada|● Funcional/);
});
function legend(field='PADRAO',visible=true,opacity=1){const layer={},d={layer,data,field,opacity,name:'Padrões de Relevo'},ctx={element,document:{createElementNS:(ns,tag)=>element(tag)},ARPIASCartography:require('../js/cartography.js'),ARPIASGeomorphology:geom,overlayDefs:[],civilDefs:[],reliefDefs:[d],map:{hasLayer:l=>visible&&l===layer},workGroup:{getLayers:()=>[]},measureGroup:{getLayers:()=>[]},selection:null};vm.createContext(ctx);vm.runInContext(tools.slice(tools.indexOf('  function styleSwatch('),tools.indexOf("  byId('legendBtn')"))+'\nthis.render=visibleLegend;',ctx);return ctx.render();}
test('the real legend displays actual classes, counts and non-risk warning only for visible relief',()=>{const box=legend();assert.equal(box.children[0].textContent,geom.legendWarning);assert.equal(box.children.filter(c=>c.className==='legend-entry').length,21);assert.match(box.textContent,/R4a1 · Colinas \(69\)/);assert.doesNotMatch(legend('PADRAO',false).textContent,/relevo|risco/)});
test('the real legend changes to six units and its swatches follow opacity',()=>{const box=legend('UnGeomorf',true,.4);assert.equal(box.children.filter(c=>c.className==='legend-entry').length,6);assert.match(box.textContent,/Unidade geomorfológica/);assert.doesNotMatch(box.textContent,/R4a1/);const swatch=box.children.find(c=>c.className==='legend-entry').children[0].children[0];assert.equal(Number(swatch.attributes['fill-opacity']),.1);assert.equal(geom.style(data,'PADRAO',data.features[0],.4).fillOpacity,.1)});
test('the actual browser Turf bundle exposes and executes every function used by the portal',()=>{
  const ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/vendor/turf.js','utf8'),ctx);const turf=ctx.window.ARPIASTurf,required=['area','length','centroid','centerOfMass','point','booleanPointInPolygon','booleanPointOnLine','distance'];required.forEach(name=>assert.equal(typeof turf[name],'function',name));
  const p={type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[[[0,0],[1,0],[1,1],[0,1],[0,0]]]}},line={type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[[0,0],[1,0]]}};
  assert.ok(turf.area(p)>1e10);assert.ok(turf.length(line)>100);assert.ok(turf.distance(turf.point([0,0]),turf.point([1,0]))>100);assert.equal(turf.booleanPointInPolygon(turf.point([.5,.5]),p),true);assert.equal(turf.booleanPointOnLine(turf.point([.5,0]),line),true);assert.equal(turf.centroid(p).geometry.coordinates.length,2);assert.equal(turf.centerOfMass(p).geometry.coordinates.length,2);
  const called=new Set([...['js/geometry.js','js/tools.js','js/report.js'].flatMap(p=>[...fs.readFileSync(p,'utf8').matchAll(/(?:ARPIASTurf|turf)\.([A-Za-z]+)/g)].map(m=>m[1]))]);assert.deepEqual([...called].sort(),required.sort());
});
